// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqnVBpN_I15-KY4XGcRtf2SVcgBEQc2A',
    appId: '1:93126403915:web:6c5983d672d94247696ace',
    messagingSenderId: '93126403915',
    projectId: 'pantri-91766',
    authDomain: 'pantri-91766.firebaseapp.com',
    storageBucket: 'pantri-91766.firebasestorage.app',
    measurementId: 'G-7CEKT05K5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChfayaQ5Mobi9DDBlwpoSkHKJ-ekkUJQU',
    appId: '1:93126403915:android:10b04d110202d773696ace',
    messagingSenderId: '93126403915',
    projectId: 'pantri-91766',
    storageBucket: 'pantri-91766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfJKuvJX3ty5Ozq-Y-1opAPLUfvJCa9s4',
    appId: '1:93126403915:ios:802b3d796ff05fe0696ace',
    messagingSenderId: '93126403915',
    projectId: 'pantri-91766',
    storageBucket: 'pantri-91766.firebasestorage.app',
    iosBundleId: 'com.example.imsh',
  );
}
